# Generated by Django 5.1.7 on 2025-03-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50, verbose_name='State Name')),
                ('stateAbbreviation', models.CharField(max_length=3, verbose_name='State Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionName', models.CharField(max_length=200, verbose_name='Attraction Name')),
                ('homeState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.state', verbose_name='Home State')),
            ],
        ),
    ]
